name: Build Workflow

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        node: ["10.x", "12.x", "14.x"]
        platform: [ubuntu-latest]
    name: Node v${{matrix.node}} ((${{matrix.platform}}))
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}
      - run: yarn install --ignore-engines
      - name: lint code
        run: yarn lerna run lint
      - name: run tests
        run: yarn lerna run test --stream
      - name: coverage
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          verbose: false
        env:
          CI: true
      
  publish:
    name: yarn publish
    runs-on: 'ubuntu-latest'
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: install dependencies
        run: yarn install --ignore-engines
      - name: publish
        run: yarn lerna publish
        




  


      